// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as CrossSvg from "./cross.svg";

((require("./Modal.css")));

var make = CrossSvg.default;

var Cross = /* module */[/* make */make];

function Modal(Props) {
  var children = Props.children;
  return ReactDom.createPortal(React.createElement("div", {
                  "aria-modal": true,
                  className: "modal-container",
                  role: "container"
                }, React.createElement("div", {
                      className: "modal-content"
                    }, children)), document.body);
}

function Modal$Header(Props) {
  var children = Props.children;
  return React.createElement("header", {
              className: "modal-header"
            }, children, React.createElement("button", {
                  className: "cross-btn",
                  title: "close Modal"
                }, React.createElement(make, { })));
}

var Header = /* module */[/* make */Modal$Header];

function Modal$Body(Props) {
  var children = Props.children;
  return React.createElement("article", {
              className: "modal-body"
            }, children);
}

var Body = /* module */[/* make */Modal$Body];

function Modal$Footer(Props) {
  var children = Props.children;
  return React.createElement("footer", {
              className: "modal-footer"
            }, children);
}

function Modal$Footer$CloseBtn(Props) {
  var children = Props.children;
  return React.createElement("button", {
              className: "close-button",
              title: "close modal"
            }, children);
}

var CloseBtn = /* module */[/* make */Modal$Footer$CloseBtn];

var Footer = /* module */[
  /* make */Modal$Footer,
  /* CloseBtn */CloseBtn
];

var make$1 = Modal;

export {
  Cross ,
  make$1 as make,
  Header ,
  Body ,
  Footer ,
  
}
/*  Not a pure module */
