// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as TimesSvg from "./times.svg";
import * as Utils$ReactHooksTemplate from "./Utils.bs.js";
import * as Button$ReactHooksTemplate from "./Button.bs.js";

((require("./App.css")));

var make = TimesSvg.default;

var Times = /* module */[/* make */make];

function App(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setText = match[1];
  var text = match[0];
  var handleTextChange = function (e) {
    return Curry._1(setText, e.target.value);
  };
  var handleClearClick = function (param) {
    return Curry._1(setText, (function (param) {
                  return "";
                }));
  };
  var wordsCountText = String(Utils$ReactHooksTemplate.countWordsInString(text)) + " words";
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", undefined, React.createElement("h3", undefined, "Words Counter"), React.createElement("span", undefined, wordsCountText)), React.createElement("main", undefined, React.createElement("textarea", {
                      placeholder: "Express yourself...",
                      value: text,
                      onChange: handleTextChange
                    })), React.createElement("footer", undefined, React.createElement(Button$ReactHooksTemplate.make, {
                      onClick: handleClearClick,
                      title: "Clear Text",
                      children: React.createElement(make, {
                            height: "20px"
                          }),
                      disabled: text.length === 0
                    })));
}

var make$1 = App;

export {
  Times ,
  make$1 as make,
  
}
/*  Not a pure module */
