// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

((require("./App.css")));

function App(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setText = match[1];
  var handleTextChange = function (e) {
    return Curry._1(setText, e.target.value);
  };
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "header"
                }, React.createElement("h3", undefined, "Words Counter")), React.createElement("main", undefined, React.createElement("textarea", {
                      placeholder: "Express yourself...",
                      value: match[0],
                      onChange: handleTextChange
                    })));
}

var make = App;

exports.make = make;
/*  Not a pure module */
