// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

((require("./Button.css")));

function className_of_categoryButton(category) {
  return "Button " + (
          category ? "secondary" : "primary"
        );
}

function Button(Props) {
  var onClick = Props.onClick;
  var title = Props.title;
  var children = Props.children;
  var match = Props.disabled;
  var disabled = match !== undefined ? match : false;
  var match$1 = Props.category;
  var category = match$1 !== undefined ? match$1 : /* SECONDARY */1;
  return React.createElement("button", {
              className: className_of_categoryButton(category),
              title: title,
              disabled: disabled,
              onClick: onClick
            }, children);
}

var make = Button;

export {
  className_of_categoryButton ,
  make ,
  
}
/*  Not a pure module */
