// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Copy$ReactHooksTemplate from "./Copy.bs.js";
import * as ReactCopyToClipboard from "react-copy-to-clipboard";
import * as Times$ReactHooksTemplate from "./Times.bs.js";
import * as Utils$ReactHooksTemplate from "./Utils.bs.js";
import * as Button$ReactHooksTemplate from "./Button.bs.js";

((require("./Home.css")));

function Home(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setText = match[1];
  var text = match[0];
  var handleTextChange = function (e) {
    return Curry._1(setText, e.target.value);
  };
  var handleClearClick = function (param) {
    return Curry._1(setText, (function (param) {
                  return "";
                }));
  };
  var wordsCountText = String(Utils$ReactHooksTemplate.countWordsInString(text)) + " words";
  return React.createElement("div", {
              className: "Home"
            }, React.createElement("header", undefined, React.createElement("h3", undefined, "Words Counter"), React.createElement("span", undefined, wordsCountText)), React.createElement("main", undefined, React.createElement("textarea", {
                      placeholder: "Express yourself...",
                      value: text,
                      onChange: handleTextChange
                    })), React.createElement("footer", undefined, React.createElement(Button$ReactHooksTemplate.make, {
                      onClick: handleClearClick,
                      title: "Clear Text",
                      children: React.createElement(Times$ReactHooksTemplate.make, {
                            height: "20px"
                          }),
                      disabled: text.length === 0
                    }), React.createElement(ReactCopyToClipboard.CopyToClipboard, {
                      text: text,
                      children: React.createElement(Button$ReactHooksTemplate.make, {
                            title: "Copy Text",
                            children: React.createElement(Copy$ReactHooksTemplate.make, {
                                  height: "20px"
                                }),
                            disabled: text.length === 0,
                            category: /* PRIMARY */0
                          })
                    })));
}

var make = Home;

export {
  make ,
  
}
/*  Not a pure module */
