// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component1$WordsCounter = require("./Component1.bs.js");
var Component2$WordsCounter = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component1$WordsCounter.make, {
          message: "Hello! Click this text."
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$WordsCounter.make, {
          greeting: "Hello!"
        }), "index2");

/*  Not a pure module */
