// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Login(Props) {
  return React.createElement("div", {
              className: "Login"
            }, React.createElement("h2", undefined, "Login Page"));
}

var make = Login;

export {
  make ,
  
}
/* react Not a pure module */
