// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


function countWordsInString(text) {
  var spacesRegEx = (/\s+/);
  if (text === "") {
    return 0;
  } else {
    return text.trim().split(spacesRegEx).length;
  }
}

export {
  countWordsInString ,
  
}
/* No side effect */
