// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function countWordsInString(text) {
  var spacesRegEx = new RegExp("\\s+");
  if (text === "") {
    return 0;
  } else {
    return text.trim().split(spacesRegEx).length;
  }
}

exports.countWordsInString = countWordsInString;
/* No side effect */
