// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict'

var React = require('react')
var ReactDOMRe = require('reason-react/src/ReactDOMRe.js')
var Component1$MyReactApp = require('./Component1.bs.js')
var Component2$MyReactApp = require('./Component2.bs.js')

ReactDOMRe.renderToElementWithId(React.createElement(Component1$MyReactApp.make, {
  message: 'Hello! Click this text.'
}), 'index1')

ReactDOMRe.renderToElementWithId(React.createElement(Component2$MyReactApp.make, {
  greeting: 'Hello!'
}), 'index2')

/*  Not a pure module */
